### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by mhartington** [formly-js/angular-formly-templates-ionic#2]
Most of the things need we can grab from the bootstrap example, but just to list what needs to be done
- [x] write the templates
- [x] bower.json
- [x] package.json
- [x] gulp or grunt (I prefer gulp)
- [ ] setup tests

Reasonings for gulp:
Ionic uses gulp for its build process, so it may be beneficial to do so.
But I see that most of formly uses grunt. 
Any preference here?

**Comment by kentcdodds** [comment]
Awesome that you're working on this. Thanks a ton. I definitely prefer webpack personally. I just haven't had the opportunity to update the template libraries to switch from grunt to webpack. Feel free to do whatever you feel is best for the build process though. They all get the job done.

One thing I really like about webpack is that you can really easily enable es6 and you can require templates, which means you don't need to worry about the `$templateCache` at all because the result is an inlined string for the template (for example, I never use `templateUrl` for anything anymore, I always just use `template: require('./my-awesome-template.html')` :-)

**Comment by kentcdodds** [comment]
But yeah, feel free to go with whatever you think is best!

**Comment by kentcdodds** [comment]
@mhartington if you're curious, I just released an egghead.io lesson on webpack: https://egghead.io/lessons/javascript-intro-to-webpack

**Comment by mhartington** [comment]
So get an initial pass done and pushed to a dev branch for now.
Still need to write some tests to make sure all is well.

Went with grunt since the vanilla templates already had a good starting point, but this may change.

https://github.com/formly-js/angular-formly-templates-ionic/tree/dev

**Comment by kentcdodds** [comment]
Fantastic! Do you think it's be possible to get a demo online like those sweet ones you guys have over on the ionic website? That'd be a cool thing to have. It would be awesome to have something we could use as a jsbin template so we could build examples and put them on the official website.

**Comment by mhartington** [comment]
hope you don't mind, but I pushed a small demo page to gh-pages

http://formly-js.github.io/angular-formly-templates-ionic/#/

**Comment by kentcdodds** [comment]
Dude, that's totally legit! I love it! Can I tweet about it now? Or would you prefer that I wait until you get more examples and work done on the lib?

**Comment by mhartington** [comment]
let me clean a few things up more on the lib and site. Plus push it to master too :smile:

**Comment by kentcdodds** [comment]
By the way, I fixed the intro example that I think you used as a template for your demo. There was a piece that I broke a while ago and never fixed. Should be a little better now :-)

http://formly-js.github.io/angular-formly/#/example/intro/introduction

**Comment by mhartington** [comment]
Finally pushed to master :grin: 

https://github.com/formly-js/angular-formly-templates-ionic/commit/abd6181be9b686576ff5293a38d23a4a7aea7ac6

Closing this for now.
